name: Gerar APK

on:
  push:
    branches:
      - main  # Gera o APK sempre que houver um push na branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Configurar dependências do Flutter
        run: flutter pub get

      - name: Gerar APK
        run: flutter build apk --release

      - name: Fazer upload do APK
        uses: actions/upload-artifact@v3
        with:
          name: betpro-future-apk
          path: build/app/outputs/flutter-apk/app-release.apk
