name: Build APK

on:
  push:
    branches:
      - main  # Gera o APK sempre que houver um push na branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0'

      - name: Configurar dependências do Flutter
        run: flutter pub get

      - name: Upload APK
  uses: actions/upload-artifact@v3
  with:
    name: apk-artifact
    path: app/build/outputs/apk/release/app-release.apk
